// Demo data for testing without Firebase

export const demoFamilies = [
  {
    id: 'family1',
    familyName: 'Johnson Family',
    membershipId: 'MEM001',
    address: {
      street: '123 Oak Street',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62701',
    },
    phoneNumber: '(555) 123-4567',
    email: 'johnson@example.com',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'family2',
    familyName: 'Williams Family',
    membershipId: 'MEM002',
    address: {
      street: '456 Maple Avenue',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62702',
    },
    phoneNumber: '(555) 234-5678',
    email: 'williams@example.com',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'family3',
    familyName: 'Anderson Family',
    membershipId: 'MEM003',
    address: {
      street: '789 Pine Road',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62703',
    },
    phoneNumber: '(555) 345-6789',
    email: 'anderson@example.com',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'family4',
    familyName: 'Martinez Family',
    membershipId: 'MEM004',
    address: {
      street: '321 Elm Street',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62704',
    },
    phoneNumber: '(555) 456-7890',
    email: 'martinez@example.com',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'family5',
    familyName: 'Davis Family',
    membershipId: 'MEM005',
    address: {
      street: '654 Birch Lane',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62705',
    },
    phoneNumber: '(555) 567-8901',
    email: 'davis@example.com',
    photoUrl: '',
    isActive: true,
  },
];

export const demoMembers = [
  {
    id: 'member1',
    familyId: 'family1',
    userId: 'demo-user-1',
    firstName: 'John',
    lastName: 'Johnson',
    email: 'john.johnson@example.com',
    phoneNumber: '(555) 123-4567',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member2',
    familyId: 'family1',
    userId: null,
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@example.com',
    phoneNumber: '(555) 123-4567',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member3',
    familyId: 'family1',
    userId: null,
    firstName: 'Emma',
    lastName: 'Johnson',
    email: '',
    phoneNumber: '',
    role: 'child',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member4',
    familyId: 'family2',
    userId: null,
    firstName: 'Michael',
    lastName: 'Williams',
    email: 'michael.williams@example.com',
    phoneNumber: '(555) 234-5678',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member5',
    familyId: 'family2',
    userId: null,
    firstName: 'Jennifer',
    lastName: 'Williams',
    email: 'jennifer.williams@example.com',
    phoneNumber: '(555) 234-5678',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member6',
    familyId: 'family3',
    userId: null,
    firstName: 'David',
    lastName: 'Anderson',
    email: 'david.anderson@example.com',
    phoneNumber: '(555) 345-6789',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member7',
    familyId: 'family3',
    userId: null,
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.anderson@example.com',
    phoneNumber: '(555) 345-6789',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member8',
    familyId: 'family4',
    userId: null,
    firstName: 'Carlos',
    lastName: 'Martinez',
    email: 'carlos.martinez@example.com',
    phoneNumber: '(555) 456-7890',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member9',
    familyId: 'family5',
    userId: null,
    firstName: 'Robert',
    lastName: 'Davis',
    email: 'robert.davis@example.com',
    phoneNumber: '(555) 567-8901',
    role: 'parent',
    photoUrl: '',
    isActive: true,
  },
];

export const demoUser = {
  uid: 'demo-user-1',
  email: 'demo@example.com',
  emailVerified: true,
};

export const demoUserRole = {
  role: 'member',
  permissions: {
    canViewDirectory: true,
    canEditFamily: false,
    canManageAll: false,
  },
};

export const demoEvents = [
  {
    id: 'event1',
    title: 'Sunday Service',
    description: 'Weekly Sunday worship service',
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event2',
    title: 'Bible Study',
    description: 'Wednesday evening Bible study and prayer',
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 1.5 * 60 * 60 * 1000).toISOString(),
    location: 'Fellowship Hall',
    isAllDay: false,
  },
  {
    id: 'event3',
    title: 'Youth Group Meeting',
    description: 'Monthly youth group gathering',
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    location: 'Youth Center',
    isAllDay: false,
  },
  {
    id: 'event4',
    title: 'Community Potluck',
    description: 'Monthly fellowship potluck dinner',
    startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days from now
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Fellowship Hall',
    isAllDay: true,
  },
  {
    id: 'event5',
    title: 'Sunday Service',
    description: 'Weekly Sunday worship service',
    startDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(), // 9 days from now
    endDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event6',
    title: 'Choir Practice',
    description: 'Weekly choir rehearsal',
    startDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days from now
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
    location: 'Music Room',
    isAllDay: false,
  },
];

export const demoAppSettings = {
  googleCalendarId: 'demo-calendar',
  googleApiKey: 'demo-api-key',
  churchName: 'St. Thomas Church',
  churchAddress: '100 Church Street, Springfield, IL 62701',
  contactEmail: 'info@stthomas.org',
};
