// Demo data for testing without Firebase

export const demoFamilies = [
  {
    id: 'family1',
    familyName: 'Johnson Family',
    membershipId: 'MEM001',
    address: {
      street: '123 Oak Street',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62701',
    },
    phoneNumber: '(555) 123-4567',
    email: 'johnson@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    id: 'family2',
    familyName: 'Williams Family',
    membershipId: 'MEM002',
    address: {
      street: '456 Maple Avenue',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62702',
    },
    phoneNumber: '(555) 234-5678',
    email: 'williams@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    id: 'family3',
    familyName: 'Anderson Family',
    membershipId: 'MEM003',
    address: {
      street: '789 Pine Road',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62703',
    },
    phoneNumber: '(555) 345-6789',
    email: 'anderson@example.com',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'family4',
    familyName: 'Martinez Family',
    membershipId: 'MEM004',
    address: {
      street: '321 Elm Street',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62704',
    },
    phoneNumber: '(555) 456-7890',
    email: 'martinez@example.com',
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'family5',
    familyName: 'Davis Family',
    membershipId: 'MEM005',
    address: {
      street: '654 Birch Lane',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62705',
    },
    phoneNumber: '(555) 567-8901',
    email: 'davis@example.com',
    photoUrl: '',
    isActive: true,
  },
];

export const demoMembers = [
  {
    id: 'member1',
    familyId: 'family1',
    userId: 'demo-user-1',
    firstName: 'John',
    lastName: 'Johnson',
    email: 'john.johnson@example.com',
    phoneNumber: '(555) 123-4567',
    role: 'parent',
    isHeadOfHousehold: true,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member2',
    familyId: 'family1',
    userId: null,
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@example.com',
    phoneNumber: '(555) 123-4567',
    role: 'parent',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member3',
    familyId: 'family1',
    userId: null,
    firstName: 'Emma',
    lastName: 'Johnson',
    email: '',
    phoneNumber: '',
    role: 'child',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member4',
    familyId: 'family2',
    userId: null,
    firstName: 'Michael',
    lastName: 'Williams',
    email: 'michael.williams@example.com',
    phoneNumber: '(555) 234-5678',
    role: 'parent',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member5',
    familyId: 'family2',
    userId: null,
    firstName: 'Jennifer',
    lastName: 'Williams',
    email: 'jennifer.williams@example.com',
    phoneNumber: '(555) 234-5678',
    role: 'parent',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member6',
    familyId: 'family3',
    userId: null,
    firstName: 'David',
    lastName: 'Anderson',
    email: 'david.anderson@example.com',
    phoneNumber: '(555) 345-6789',
    role: 'parent',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member7',
    familyId: 'family3',
    userId: null,
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.anderson@example.com',
    phoneNumber: '(555) 345-6789',
    role: 'parent',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member8',
    familyId: 'family4',
    userId: null,
    firstName: 'Carlos',
    lastName: 'Martinez',
    email: 'carlos.martinez@example.com',
    phoneNumber: '(555) 456-7890',
    role: 'parent',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
  {
    id: 'member9',
    familyId: 'family5',
    userId: null,
    firstName: 'Robert',
    lastName: 'Davis',
    email: 'robert.davis@example.com',
    phoneNumber: '(555) 567-8901',
    role: 'parent',
    isHeadOfHousehold: false,
    photoUrl: '',
    isActive: true,
  },
];

export const demoUser = {
  uid: 'demo-user-1',
  email: 'demo@example.com',
  emailVerified: true,
};

export const demoUserRole = {
  role: 'member',
  permissions: {
    canViewDirectory: true,
    canEditFamily: false,
    canManageAll: false,
  },
};

export const demoEvents = [
  // ── March 22 (last Sunday) ──────────────────────────────────────────────
  {
    id: 'event-mar22-qurbana',
    title: 'Holy Qurbana',
    description: 'Weekly Sunday Divine Liturgy. All are welcome to worship together.',
    startDate: '2026-03-22T09:30:00',
    endDate:   '2026-03-22T12:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  // ── March 24 (today – Tuesday) ──────────────────────────────────────────
  {
    id: 'event-mar24-prayer',
    title: 'Parish Prayer Meeting',
    description: 'Monthly intercessory prayer meeting open to all parish members.',
    startDate: '2026-03-24T19:00:00',
    endDate:   '2026-03-24T20:30:00',
    location: 'Fellowship Hall',
    isAllDay: false,
  },
  // ── March 27 (Friday) ──────────────────────────────────────────────────
  {
    id: 'event-mar27-vespers',
    title: 'Friday Evening Prayers',
    description: 'Raza & Vespers prayers led by the parish priest.',
    startDate: '2026-03-27T19:00:00',
    endDate:   '2026-03-27T20:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-mar27-choir',
    title: 'Choir Practice',
    description: 'Weekly rehearsal for the parish choir. New members welcome!',
    startDate: '2026-03-27T20:15:00',
    endDate:   '2026-03-27T21:30:00',
    location: 'Music Room',
    isAllDay: false,
  },
  // ── March 29 (Palm Sunday) ──────────────────────────────────────────────
  {
    id: 'event-mar29-palmsunday',
    title: 'Palm Sunday – Holy Qurbana',
    description: 'Commemoration of the Triumphal Entry of our Lord into Jerusalem. Palm branches will be distributed after the service.',
    startDate: '2026-03-29T09:00:00',
    endDate:   '2026-03-29T12:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-mar29-sunday-school',
    title: 'Sunday School',
    description: 'Weekly Sunday School classes for all age groups.',
    startDate: '2026-03-29T12:30:00',
    endDate:   '2026-03-29T13:30:00',
    location: 'Education Wing',
    isAllDay: false,
  },
  // ── Holy Week (Mar 30 – Apr 4) ──────────────────────────────────────────
  {
    id: 'event-mar30-holyweek',
    title: 'Holy Week Evening Prayers',
    description: 'Passion Week evening service — Monday.',
    startDate: '2026-03-30T19:00:00',
    endDate:   '2026-03-30T20:30:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-mar31-holyweek',
    title: 'Holy Week Evening Prayers',
    description: 'Passion Week evening service — Tuesday.',
    startDate: '2026-03-31T19:00:00',
    endDate:   '2026-03-31T20:30:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-apr01-holyweek',
    title: 'Holy Week Evening Prayers',
    description: 'Passion Week evening service — Wednesday.',
    startDate: '2026-04-01T19:00:00',
    endDate:   '2026-04-01T20:30:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-apr02-pesaha',
    title: 'Pesaha (Maundy Thursday)',
    description: 'Service commemorating the Last Supper of our Lord. Pesaha Appam and Paal will be distributed. Families are encouraged to observe Pesaha at home.',
    startDate: '2026-04-02T18:00:00',
    endDate:   '2026-04-02T21:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-apr03-goodfriday',
    title: 'Good Friday – Dukha Velli',
    description: 'Solemn service commemorating the crucifixion and death of our Lord Jesus Christ. Fasting is observed until 3 PM.',
    startDate: '2026-04-03T09:00:00',
    endDate:   '2026-04-03T15:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-apr04-holysat',
    title: 'Holy Saturday Prayers',
    description: 'Evening prayers and preparation for the Resurrection feast.',
    startDate: '2026-04-04T18:00:00',
    endDate:   '2026-04-04T19:30:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  // ── April 5 (Easter Sunday) ─────────────────────────────────────────────
  {
    id: 'event-apr05-easter',
    title: 'Easter Sunday – Holy Qurbana',
    description: 'Blessed Feast of the Holy Resurrection of our Lord Jesus Christ! Special Resurrection service followed by parish breakfast. All families are warmly invited.',
    startDate: '2026-04-05T08:00:00',
    endDate:   '2026-04-05T12:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-apr05-breakfast',
    title: 'Easter Parish Breakfast',
    description: 'Celebratory breakfast for the whole parish following the Resurrection Qurbana.',
    startDate: '2026-04-05T12:15:00',
    endDate:   '2026-04-05T14:00:00',
    location: 'Fellowship Hall',
    isAllDay: false,
  },
  // ── April 10 (Friday) ───────────────────────────────────────────────────
  {
    id: 'event-apr10-vespers',
    title: 'Friday Evening Prayers',
    description: 'Raza & Vespers prayers led by the parish priest.',
    startDate: '2026-04-10T19:00:00',
    endDate:   '2026-04-10T20:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-apr10-choir',
    title: 'Choir Practice',
    description: 'Weekly choir rehearsal.',
    startDate: '2026-04-10T20:15:00',
    endDate:   '2026-04-10T21:30:00',
    location: 'Music Room',
    isAllDay: false,
  },
  // ── April 12 (Sunday) ───────────────────────────────────────────────────
  {
    id: 'event-apr12-qurbana',
    title: 'Holy Qurbana',
    description: 'Weekly Sunday Divine Liturgy.',
    startDate: '2026-04-12T09:30:00',
    endDate:   '2026-04-12T12:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  {
    id: 'event-apr12-sunday-school',
    title: 'Sunday School',
    description: 'Weekly Sunday School classes for all age groups.',
    startDate: '2026-04-12T12:30:00',
    endDate:   '2026-04-12T13:30:00',
    location: 'Education Wing',
    isAllDay: false,
  },
  // ── April 15 (Wednesday) ────────────────────────────────────────────────
  {
    id: 'event-apr15-biblestudy',
    title: 'Bible Study',
    description: 'Mid-week Bible study and reflection. This month: The Gospel of John.',
    startDate: '2026-04-15T19:30:00',
    endDate:   '2026-04-15T21:00:00',
    location: 'Fellowship Hall',
    isAllDay: false,
  },
  // ── April 18 (Saturday) ─────────────────────────────────────────────────
  {
    id: 'event-apr18-youth',
    title: 'Youth Fellowship Meeting',
    description: 'Monthly gathering for parish youth (grades 6–12). Games, discussion, and prayer.',
    startDate: '2026-04-18T17:00:00',
    endDate:   '2026-04-18T20:00:00',
    location: 'Youth Center',
    isAllDay: false,
  },
  // ── April 19 (Sunday) ───────────────────────────────────────────────────
  {
    id: 'event-apr19-qurbana',
    title: 'Holy Qurbana',
    description: 'Weekly Sunday Divine Liturgy.',
    startDate: '2026-04-19T09:30:00',
    endDate:   '2026-04-19T12:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  // ── April 25 (Saturday) ─────────────────────────────────────────────────
  {
    id: 'event-apr25-potluck',
    title: 'Parish Family Potluck',
    description: 'Monthly fellowship dinner. Please bring a dish to share! Sign-up sheet available after Sunday Qurbana.',
    startDate: '2026-04-25T17:00:00',
    endDate:   '2026-04-25T20:00:00',
    location: 'Fellowship Hall',
    isAllDay: false,
  },
  // ── April 26 (Sunday) ───────────────────────────────────────────────────
  {
    id: 'event-apr26-qurbana',
    title: 'Holy Qurbana',
    description: 'Weekly Sunday Divine Liturgy.',
    startDate: '2026-04-26T09:30:00',
    endDate:   '2026-04-26T12:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  // ── May 3 (Sunday) ──────────────────────────────────────────────────────
  {
    id: 'event-may03-qurbana',
    title: 'Holy Qurbana',
    description: 'Weekly Sunday Divine Liturgy.',
    startDate: '2026-05-03T09:30:00',
    endDate:   '2026-05-03T12:00:00',
    location: 'Main Sanctuary',
    isAllDay: false,
  },
  // ── May 9 (Saturday) ────────────────────────────────────────────────────
  {
    id: 'event-may09-womens',
    title: "Women's Fellowship Meeting",
    description: "Monthly meeting of the St. Thomas Women's Fellowship (Vanitha Samajam).",
    startDate: '2026-05-09T10:00:00',
    endDate:   '2026-05-09T12:30:00',
    location: 'Fellowship Hall',
    isAllDay: false,
  },
  // ── May 17 (Sunday – Feast of St. Thomas) ──────────────────────────────
  {
    id: 'event-may17-feast',
    title: 'Feast of St. Thomas the Apostle',
    description: 'Annual patronal feast day of our parish. Special Solemn Qurbana followed by parish feast lunch. All parishioners and guests are warmly welcomed.',
    startDate: '2026-05-17T09:00:00',
    endDate:   '2026-05-17T14:00:00',
    location: 'Main Sanctuary & Fellowship Hall',
    isAllDay: false,
  },
];

// Contribution categories are imported directly from QuickBooks (as QB "accounts" or "classes").
// Do not hard-code categories here — they will be whatever QB exports.
// These demo entries mirror a typical QB contribution export.
export const demoContributions = [
  { id: 'contrib-1', familyId: 'family1', amount: 500.00, date: '2026-01-12', category: 'Tithe', description: 'January Tithe', fiscalYear: 2026 },
  { id: 'contrib-2', familyId: 'family1', amount: 500.00, date: '2026-02-09', category: 'Tithe', description: 'February Tithe', fiscalYear: 2026 },
  { id: 'contrib-3', familyId: 'family1', amount: 500.00, date: '2026-03-08', category: 'Tithe', description: 'March Tithe', fiscalYear: 2026 },
  { id: 'contrib-4', familyId: 'family1', amount: 250.00, date: '2026-01-01', category: 'Building Fund', description: 'Annual Building Fund Pledge', fiscalYear: 2026 },
  { id: 'contrib-5', familyId: 'family1', amount: 100.00, date: '2026-02-22', category: 'Lenten Collection', description: 'Lenten Special Collection', fiscalYear: 2026 },
  { id: 'contrib-6', familyId: 'family1', amount: 75.00,  date: '2026-03-15', category: 'Outreach', description: 'Community Outreach Fund', fiscalYear: 2026 },
];

export const demoDocuments = [
  {
    id: 'doc1',
    title: '2026 Charitable Contribution Letter',
    description: 'Official tax acknowledgment letter for all donations made in 2026.',
    type: 'tax-letter',
    year: 2026,
    url: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/sample.pdf',
    uploadedAt: '2026-01-15T10:00:00',
  },
  {
    id: 'doc2',
    title: '2026 Annual Parish Report',
    description: 'Summary of parish activities, financials, and membership for 2026.',
    type: 'annual-report',
    year: 2026,
    url: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/sample.pdf',
    uploadedAt: '2026-02-01T10:00:00',
  },
  {
    id: 'doc3',
    title: '2026 Stewardship Pledge Receipt',
    description: 'Receipt confirming your stewardship pledge for the 2026 parish year.',
    type: 'receipt',
    year: 2026,
    url: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/sample.pdf',
    uploadedAt: '2026-01-10T10:00:00',
  },
];

export const demoAppSettings = {
  googleCalendarId: 'demo-calendar',
  googleApiKey: 'demo-api-key',
  churchName: 'St. Thomas Church',
  churchAddress: '100 Church Street, Springfield, IL 62701',
  contactEmail: 'info@stthomas.org',
};
